<div id="who" class="subcontent">
    <div class="nevitech-slider">
        <div class="nevitech-slider-prev"></div>
        <div class="nevitech-slider-viewport" style="width: 800px;height: 400px;overflow: hidden">
            <div>
                <div class="nevitech-slider-item">
                    <div class="grid_5">
                        <img src="/images/who/dai.jpg" alt="Dai Tran Hoang" width="380" height="380" />
                    </div>
                    <div class="grid_5">
                        <h2>Dai Tran Hoang</h2>

                        <p>Tran Hoang Dai is one of the main developer at Nevitech. He focuses on the back-end development, aims to make the infrastructure cooperate nicely with Nevitech solution, thus provides the best experience for Nevitech's customers.</p><br/>
    					<p>During his free time, he enjoys working out in the gym, and play some RPG computer games.</p>
                    </div>
                </div>

                <div class="nevitech-slider-item">
                    <div class="grid_5">
                        <img src="/images/who/profilepic.png" alt="Prashant Palikhe" width="380" height="380" />
                    </div>
                    <div class="grid_5">
                        <h2>Prashant Palikhe</h2>

                        <p>Prashant is an allround developer at Nevitech. He combines his skills very well with his pursit for pixel-perfection. His specialities include HTML(5)/CSS, jQuery, PHP, Zend Framework, Wordpress and Magento.</p><br />
                        <p>Besides, Prashant enjoys physical activities. He loves to play basketball and destress with an hour in the gym everyday. In the weekend, he is outside at the neighbourhood park playing basketball with his friends.</p>
                    </div>
                </div>
            </div>
        </div>
        <div class="nevitech-slider-next"></div>
        <div>
        </div>
    </div>
</div>
