<section id="customers" class="section">
    <div class="container_12">
        <ul>
            <li class="grid_3">
                <img class="lazy" src="/images/grey.gif" data-original="/images/mozkids.png" alt="" />
                <br />
                <div class="quote">
					<span class="quote-inner">
						<span class="parentheses open">&ldquo;</span>
						<span class="string">
                            They work wonderfully.
						</span>
						<span class="parentheses close">&rdquo;</span>
					</span>

				</div>
            </li>
        </ul>
    </div>
</section>
