<div id="footer">
    <div class="header">
        <div class="container_12">
            <div class="grid_6">
                <h2>Find us at</h2>
            </div>
            <div class="grid_6">
                <h2>About us</h2>
            </div>
        </div>
    </div>
    <div class="content container_12">
        <ul class="social grid_6">
            <li><a class="t" title="@NevitechSupport" href="https://www.twitter.com/NevitechSupport" target="_blank"></a></li>
            <li><a class="fb" title="Facebook" href="https://www.facebook.com/Nevitech?ref=hl" target="_blank"></a></li>
            <li><a class="gp" title="Google Plus" href="https://plus.google.com/u/0/b/104140773803335148277/104140773803335148277/posts" target="_blank"></a></li>
            <li><a class="m" title="Email" href="mailto:info@nevitech.com" target="_blank"></a></li>
        </ul>

        <div class="grid_6">
            <div class="logo"></div>

            <p>Nevitech is a web design &amp; web development company based in Utrecht, the Netherlands</p>

            <p>We are dedicated to design, develop and deploy website and applications that our customers love.</p>

            <a data-toggle="subcontent" data-target="#who" data-callback="#footer" href="javascript:void(0);">Our team</a>
        </div>
    </div>
    <div class="footer">
        <div class="container_12">
            <div class="grid_12">
                <p class="copyright">Copyright &copy; 2012 NEVITECH. All rights reserved.</p>
                <p class="contact">(06-34311489) &nbsp;&nbsp; info@nevitech.com</p>
            </div>
        </div>
    </div>
</div>
