<div id="header">
    <div class="container_12">
        <div class="grid_12">
            <div id="logo">
                <a href="/" title="Nevitech"></a>
            </div>
            <ul class="nav">
                <li><a data-toggle="subcontent" data-target="#who" data-callback="#header" href="#">Who</a></li>
                <li><a class="goto" data-target="#what" href="#what">What</a></li>
                <li><a data-toggle="subcontent" data-target="#where" data-callback="#header" href="#">Where</a></li>
                <li><a class="goto" data-target="#projects" href="#projects">Portfolio</a></li>
            </ul>
        </div>
    </div>
</div>
