<?php if ($this->isHome()) : ?>

    <div id="banner">
        <div class="container_12">
            <div class="grid_12">
                <div class="item">
                    <img src="<?php echo $this->baseUrl(); ?>/images/design.png" alt="" title="" />
                    <div class="content">
                        <h2>Have a website that will make a difference</h2>
                        <p>Nevitech is a young and dynamic software and web development company. We are committed to provide the most elegant and creative designs around.</p>

                        <?php echo $this->partial('contact.phtml'); ?>
                    </div>
                </div>
            </div>
        </div>
    </div>

<?php endif; ?>
