<section id="what" class="container_12 section">
    <ul>
        <li class="grid_3 design">
            <span></span>
            <h2>Design</h2>
            <p>Every project starts with a design. We create your design from scratch making sure your website looks and feels exactly the way you want it.</p>
        </li>

         <li class="grid_3 develop">
            <span></span>
            <h2>Develop</h2>
            <p>We follow structured agile development methodology flexible enough to meet customer's evolving needs and requirements. </p>
        </li>

         <li class="grid_3 manage">
            <span></span>
            <h2>Manage</h2>
            <p>Do you want to update and manage the content of your website? We work with popular Content Management Systems (CMS) such as Wordpress and Drupal to help you do just that.</p>
        </li>

         <li class="grid_3 ecommerce">
            <span></span>
            <h2>E-commerce</h2>
            <p>Would you like to have your own online store? With our knowledge and your ideas, we can make that happen!</p>
        </li>
    </ul>
</section>
