<a href="#contactModal" role="button" class="btn contact" data-toggle="modal">Contact us</a>

<div id="contactModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="contactModalLabel" aria-hidden="true">
    <div class="modal-header">
        <h3 id="contactModalLabel">Contact us</h3>
    </div>
    <div class="modal-body">
        <?php echo new Application_Form_Contact(); ?>
    </div>
</div>