<?php if ($this->pageCount): ?>
    <div class="pagination grid_12">
        <ul>
            <?php if (isset($this->previous)): ?>
                <li><a href="<?php echo $this->url(array('page' => $this->previous)); ?>">&laquo;</a></li>
            <?php else: ?>
                <li class="disabled"><a href="#">&laquo;</a></li>
            <?php endif; ?>

            <?php foreach ($this->pagesInRange as $page) : ?>
                <?php if ($page == $this->current) : ?>
                    <li class="active"><a href="#"><?php echo $page; ?></a></li>
                <?php else : ?>
                    <li><a href="<?php echo $this->url(array('page' => $page)); ?>"><?php echo $page; ?></a></li>
                <?php endif; ?>
            <?php endforeach; ?>

            <?php if (isset($this->next)): ?>
                <li><a href="<?php echo $this->url(array('page' => $this->next)); ?>">&raquo;</a></li>
            <?php else: ?>
                <li class="disabled"><a href="#">&raquo;</a></li>
            <?php endif; ?>
        </ul>
    </div>
<?php endif; ?>