<!doctype html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
	<head>
        <meta charset="utf-8" />

        <!-- Use the .htaccess and remove these lines to avoid edge case issues.
             More info: h5bp.com/b/378 -->
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

        <title>Nevitech</title>
        <meta name="description" content="Nevitech" />
        <meta name="keywords" content="keywords', 'design company, web design company services, website development information, web design services company, web software development company, software and web development company, web development services company, company web development, website content development, website development php, Web Design Company, Utrecht Web Design, Web Design Utrecht, Wordpress web developer, Web Development Company, CMS development" />

        <!-- Mobile viewport optimized: j.mp/bplateviewport -->
        <meta name="viewport" content="width=device-width,initial-scale=1" />

        <!-- Place favicon.ico and apple-touch-icon.png in the root directory: mathiasbynens.be/notes/touch-icons -->

        <link rel="stylesheet" href="css/960.css" />
        <link rel="stylesheet" href="css/min.css" />
        <link rel="stylesheet" href="css/style.css" />
        <!-- <link rel="stylesheet" href="css/style.css" /> -->

        <!-- More ideas for your <head> here: h5bp.com/d/head-Tips -->

        <!-- All JavaScript at the bottom, except for Modernizr / Respond. -->
        <script src="/js/modernizr.custom.97074.js"></script>
	</head>
	<body >
        <?php $this->showMessages(); ?>

        <div id="wrap">

            <?php
                echo $this->action('header', 'index');
                echo $this->action('slideshow', 'index');
            ?>

            <div id="container" class="<?php echo Zend_Controller_Front::getInstance()->getRequest()->getControllerName(); ?> clearfix">
                <?php echo $this->layout()->content; ?>
            </div>

            <?php
                echo $this->action('footer', 'index');
                echo $this->action('subcontent', 'index');
            ?>
        </div>

        <script src="//ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
        <script>window.jQuery || document.write('<script src="js/vendor/jquery-1.8.3.min.js"><\/script>')</script>
        <!--<script src="js/min.js"></script>-->
        <script src="js/bootstrap-modal.js"></script>
        <script src="js/jquery.validate.js"></script>
        <script src="js/jquery.lazyload.js"></script>
        <script src="js/jquery.touchslider.js"></script>
        <script src="js/nevitech.js"></script>

        <!-- Prompt IE 6 users to install Chrome Frame. Remove this if you want to support IE 6.
             chromium.org/developers/how-tos/chrome-frame-getting-started -->
        <!--[if lt IE 7 ]>
            <script src="//ajax.googleapis.com/ajax/libs/chrome-frame/1.0.3/CFInstall.min.js"></script>
            <script>window.attachEvent('onload',function(){CFInstall.check({mode:'overlay'})})</script>
        <![endif]-->
	</body>
</html>
