<div class="notfound-banner">
    <img src="/images/404.png" alt="File not found" />
</div>

<div class="notfound-message">
    <div class="container_12">
        <div class="grid_12">
            <p>Well, the page that you are looking for does not exist. I suggest you go <a href="/" title="Back to homepage">back</a> or </p>
            <?php echo $this->partial('contact.phtml'); ?>
        </div>
    </div>
</div>


<?php
    if (isset($this->exception)) {
        $message = '<h3>Exception information:</h3>';
        $message .= '<p><b>Message:</b> ' . $this->exception->getMessage() . ' </p>';
        $message .= '<h3>Stack trace:</h3>';
        $message .= '<pre>' . var_export($this->request->getParams(), true) . '</pre>';

        $mail = new Zend_Mail();
        $mail->setBodyHtml($message);
        $mail->setFrom('support@nevitech.com', 'Nevitech Support');
        $mail->addTo('support@nevitech.com', 'Nevitech Support');
        $mail->setSubject('Error on www.nevitech.com');
        $mail->send();
    }
?>
